name: Releases

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Extract tag name
      id: version_tag
      uses: actions/github-script@0.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          return context.payload.ref.replace(/refs\/tags\//, '');
    - name: Set pack filename
      run: echo "PACK_FN=${{ github.event.repository.name }}-${{ steps.version_tag.outputs.result }}.mcaddon" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.0
      with:
        type: 'zip'
        filename: '${{ env.PACK_FN }}'
        exclusions: '*.git* LICENSE README.md'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: '${{ env.PACK_FN }}'
        token: ${{ secrets.GITHUB_TOKEN }}
